name: manual run

on:
  schedule:
      # every 6 hours
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:      
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/docker/github-contribution-grid-snake.svg
            dist/docker/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/docker/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
